-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- TODO: manual review — unknown section 'listener {' on line 4
hl.config({
    general = {
        before_sleep_cmd = "/usr/bin/qs -c noctalia-shell ipc call lockScreen lock", -- lock before suspend.
    },
})

