-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local text_color = "rgba(1f4d6fFF)"
local entry_background_color = "rgba(1e1e2e11)"
local entry_border_color = "rgba(6c708655)"
local entry_color = "rgba(1f4d6fFF)"
local font_family = "Rubik"
local font_family_clock = "Space Grotesk DemiBold"
local font_material_symbols = "Material Symbols Rounded"

-- TODO: manual review — unknown section 'background {' on line 9
-- TODO: manual review — unknown section 'input-field {' on line 17

-- TODO: manual review — unknown section 'label {' on line 33

-- TODO: manual review — unknown section 'label {' on line 44
-- Caps Lock Warning

-- TODO: manual review — unknown section 'label {' on line 56
-- Clock
-- TODO: manual review — unknown section 'label {' on line 67
-- Date

-- TODO: manual review — unknown section 'label {' on line 79
-- User

-- TODO: manual review — unknown section 'label {' on line 94
-- Status
