-- Generated by nwg-displays on 2025-08-05 at 18:05:53. Do not edit manually.

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "HDMI-A-1",
    mode = "3440x1440@100.0",
    position = "0x1440",
    scale = "1.0",
})

hl.monitor({
    output = "DP-1",
    mode = "3440x1440@100.0",
    position = "0x0",
    scale = "1.0",
})

