-- ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
-- ┃                    Autostart Configuration                  ┃
-- ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: ~/.config/hypr/config/defaults.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("config.defaults")

-- Autostart wiki https://wiki.hyprland.org/0.45.0/Configuring/Keywords/#executing #

--exec-once = swaybg -o \* -i /home/vv0rth/Pictures/Wallpaper/Default* -m fill
--exec-once = waybar &
--exec-once = swaync &
--exec-once = nm-applet --indicator &

-- ## Video Wallpaper
--

-- ## Slow app launch fix

-- ## Idle configuration

hl.on("hyprland.start", function()
    hl.exec_cmd("dms run &")
    hl.exec_cmd("fcitx5 -d &")
    hl.exec_cmd("bash -c \"mkfifo /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob && tail -f /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob | wob & disown\" &")
    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1 &")
    hl.exec_cmd("mpvpaper -o \"--loop-file inf\" '*' ~/Pictures/Wallpaper/Video/Interp.mov")
    hl.exec_cmd("systemctl --user import-environment &")
    hl.exec_cmd("hash dbus-update-activation-environment 2>/dev/null &")
    hl.exec_cmd("dbus-update-activation-environment --systemd &")
    hl.exec_cmd("$idlehandler")
end)

