-- ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
-- ┃                     Defaults Configuration                  ┃
-- ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

filemanager = "nautilus"
webbrowser = "zen-browser"
applauncher = "rofi -show combi -modi run,window,combi,drun -combi-modi drun,run,window"
terminal = "kitty"
idlehandler = "swayidle -w timeout 300 'swaylock -f -c 000000' before-sleep 'swaylock -f -c 000000'"
capturing = "grim -g \"$(slurp)\" - | swappy -f -"
