-- ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
-- ┃                     Monitor Configuration                   ┃
-- ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

-- Monitor wiki https://wiki.hyprland.org/0.45.0/Configuring/Monitors/

--monitor = , preferred, auto, 1

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "HDMI-A-1",
    mode = "3440x1440@100.0",
    position = "0x1440",
    scale = "1.0",
})

hl.monitor({
    output = "DP-1",
    mode = "3440x1440@100.0",
    position = "0x0",
    scale = "1.0",
})

-- If you need to scale things like steam etc, please uncomment these lines.
-- Adjust GDK_SCALE accordingly to your liking.
--xwayland {
--  force_zero_scaling = true       # Unscale XWayland
--}

--env = GDK_SCALE, 1.25                   # GDK Scaling Factor
